### ISSUE TITLE
Kod geliştirmesi

### ISSUE THREAD

**Issue by gurkanakdeniz** [umutcanbolat/instant-username-search-api#2]
https://github.com/umutcanbolat/instant-username-search-api/blob/42c32fbce234b9cb3f5d5300e554569feadcae08/src/main/java/com/umutcanbolat/instantusernamesearchapi/controller/UserController.java#L37

```
public class Site { 
        private String url;
        private String urlMain;
        private String errorType;
        private String errorMsg;  
        //get set
}
```
şeklinde sınıf oluşturursan parse etme işlemini aşağıdaki gibi yapar for ile dönmen gerekmez kod daha temiz olur.

```
   Gson gson = new Gson();
   JsonReader reader = new JsonReader(new FileReader(sitesFile));        
   Map<String, Site> data  = gson.fromJson(reader, new TypeToken<Map<String, Site>>() {}.getType());
        
   Site site = data.get(service.toLowerCase()); // dosyada lowercase olarak tut Twitter yerine twitter
    //..bla bla

```

**Comment by umutcanbolat** [comment]
JSON dosyasını başka bir yerden çektim. Value kısmı her zaman senin attığın gibi değil. Mesela:

Facebook için `regexCheck` diye alan varken, instagram için `errorMsg` var. Bu yüzden tek bir modele indirgeyemedim. (şimdilik)

```json
"Facebook": {
    "url": "https://www.facebook.com/{}",
    "urlMain": "https://www.facebook.com/",
    "errorType": "status_code",
    "regexCheck": "^[a-zA-Z0-9]{4,49}(?<!.com|.org|.net)$"
  },
"Instagram": {
    "url": "https://www.instagram.com/{}",
    "urlMain": "https://www.instagram.com/",
    "errorType": "message",
    "errorMsg": "The link you followed may be broken"
  }
```

Yapıyı düzeltip, JSON'ı diziye çevirdikten sonra dediğin gibi yapıcam.

Katkı için sağ ol :)

**Comment by gurkanakdeniz** [comment]
her zaman :)
https://stackoverflow.com/questions/4802887/gson-how-to-exclude-specific-fields-from-serialization-without-annotations
